# This workflow checks if the release and prerelease manifest is in sync.

name: Check Manifest Sync

on:
  pull_request:
    branches:
      - main

jobs:
  Check-Manifest-Sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Compare prerelease and release manifests semver
        env:
          PRERELEASE_MANIFEST_PATH: .github/prerelease-manifest.json
          RELEASE_MANIFEST_PATH: .github/release-manifest.json
        # The prerelease is not allowed to be an older version than the release
        run: |
          echo "Comparing prerelease and release manifests"
          npm install semver
          PRERELEASE_VERSION=$(jq -r '.["."]' $PRERELEASE_MANIFEST_PATH)
          RELEASE_VERSION=$(jq -r '.["."]' $RELEASE_MANIFEST_PATH)
          echo "Prerelease version: $PRERELEASE_VERSION"
          echo "Release version: $RELEASE_VERSION"
          node -e "
          const semver = require('semver');
          const prereleaseVersion = '$PRERELEASE_VERSION';
          const releaseVersion = '$RELEASE_VERSION';
          if (!prereleaseVersion || !releaseVersion) {
          console.error('One of the versions is undefined');
          process.exit(1);
          }
            if (semver.lt(prereleaseVersion, releaseVersion)) {
            console.log('Prerelease version is older than release version');
            process.exit(1);
          } else {
            console.log('Prerelease version is valid');
          }
          "
